### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by sgentile** [graphqlwtf/graphql.wtf-graphql-helix-nextjs#2]
Great video - is there anything special that needs to be done to support subscriptions ?

**Comment by notrab** [comment]
Hey 👋🏻 

Thank you 🙏🏻 

You might be interested in [this tutorial](https://www.howtographql.com/typescript-helix/9-subscriptions/) that shows you using Fastify with Helix to support Subscriptions.

**Comment by sgentile** [comment]
For clarification :  nextjs with helix 

(and also we are using graphql-mesh)
